// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpdmdzzjjjqrrwrbrjti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wZG1kenpqampxcnJ3cmJyanRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTgzMTAsImV4cCI6MjA3MjczNDMxMH0.nHmK7ORTfe24Zaomw8XaLzpDqOz9gfVXiOFHvmtA2gM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});